# Generated by Django 4.2 on 2024-06-23 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yt_Stat',
            fields=[
                ('stat_id', models.BigAutoField(db_column='stat_id', primary_key=True, serialize=False)),
                ('yt_url', models.TextField(db_column='yt_url')),
                ('yt_title', models.CharField(db_column='yt_title', max_length=200)),
                ('convert_type', models.CharField(db_column='convert_type', max_length=5)),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', null=True)),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', null=True)),
                ('img_url', models.TextField(db_column='img_url', null=True)),
                ('cuser', models.ForeignKey(blank=True, db_column='cuser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Yt_Stat',
            },
        ),
        migrations.CreateModel(
            name='Yt_Stat_tags',
            fields=[
                ('stat_did', models.BigAutoField(db_column='stat_did', primary_key=True, serialize=False)),
                ('tag_name', models.CharField(db_column='tag_name', max_length=150, unique=True)),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', null=True)),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', null=True)),
                ('stat_id', models.ForeignKey(db_column='stat_id', on_delete=django.db.models.deletion.CASCADE, to='basic.yt_stat')),
            ],
            options={
                'db_table': 'Yt_Stat_tags',
            },
        ),
    ]
