# Generated by Django 4.2 on 2024-06-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yt_stat_tags',
            name='tag_name',
            field=models.CharField(db_column='tag_name', max_length=150),
        ),
    ]
